/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../api.schema';

import { api } from '../../..';
export type OperatingTimesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type OperatingTimesQueryResult = { __typename?: 'Query', operatingTimes: Array<{ __typename?: 'OperatingTime', id: number, day?: Types.DayType | null, opens?: string | null, closes?: string | null }> };


export const OperatingTimesDocument = `
    query operatingTimes {
  operatingTimes {
    id
    day
    opens
    closes
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    operatingTimes: build.query<OperatingTimesQueryResult, OperatingTimesQueryVariables | void>({
      query: (variables) => ({ document: OperatingTimesDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useOperatingTimesQuery, useLazyOperatingTimesQuery } = injectedRtkApi;

